export const TOKEN_VALID = 'TOKEN_VALID';
export const AUTHENTICATION_SUCCEED = 'AUTHENTICATION_SUCCEED';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESHING_SUCCEED = 'REFRESHING_SUCCEED';
export const REFRESHING_FAILED = 'REFRESHING_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
